{
  parserClass="net.kenro.ji.jin.purescript.parser.PSParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="net.kenro.ji.jin.purescript.psi"
  psiImplPackage="net.kenro.ji.jin.purescript.psi.impl"

  elementTypeHolderClass="net.kenro.ji.jin.purescript.psi.PSTypes"
  elementTypeClass="net.kenro.ji.jin.purescript.psi.PSElementType"
  tokenTypeClass="net.kenro.ji.jin.purescript.psi.PSTokenType"

  psiImplUtilClass="net.kenro.ji.jin.purescript.psi.impl.PSPsiImplUtil"

  tokens = [
    ID = "regexp:\w+"
    space='regexp:\s+'
    OP_PAR_LEFT = "("
    OP_PAR_RIGHT = ")"
  ]
}

PSFile ::= item_*

private item_ ::= (ModuleDeclaration)

Identifier ::= ID

// Module

ModuleName ::=
  Identifier ['.' ModuleName]

ModuleExport ::=
     Identifier [',' ModuleExport]

ModuleExports ::=
  '(' ModuleExport ')'

ModuleDeclaration ::=
  'module' ModuleName ModuleExports? 'where'